### ISSUE TITLE
Help finding train/test files

### ISSUE THREAD

**Issue by nnkennard** [fajri91/NeuralRST#3]
Hello,

Thank you so much for this useful implementation! I am hoping to use it in my project.

I tried to follow the instructions in the README, running the command

`python train_rst_parser.py --batch_size=8 --experiment=exp1 --drop_prob=0.5 --ada_eps=1e-6 --gamma=1e-6 --use_dynamic_oracle=1 --start_dynamic_oracle=20`

Unfortunately, this results in an error as the file `Data/NeuralRST/rst.train312` (default value of the flag `--train`) cannot be found. Could you please let me know how this file is created from the RST Dataset? Is this the output of the RSTExtractor repository?

Thank you!

**Comment by fajri91** [comment]
Hi there,

Sorry for the late reply, I didn't see the notification.
Do you still need it? I use the preprocessed train/test/dev set by the original author (I emailed them).
I can send it to you if you still need it. Please drop an email.

Regards,

**Comment by wangwang110** [comment]
> Hi there,
> 
> Sorry for the late reply, I didn't see the notification.
> Do you still need it? I use the preprocessed train/test/dev set by the original author (I emailed them).
> I can send it to you if you still need it. Please drop an email.
> 
> Regards,

need the processed  train/test/dev set， can you send me an copy .  thank you so much .  email: 1448478219@qq.com

**Comment by nnkennard** [comment]
Thanks for your reply! Yes, I would still like to have the dataset files if possible. Please email me at kennard@cs.umass.edu. Thank you so much!

**Comment by fajri91** [comment]
Email sent, please check.

**Comment by YTZ01** [comment]
Hello, I would like to have the dataset files as well if possible（which include the rst.train312 file）. Please email me at yutongz@bupt.edu.cn      I would really appreciate! Thank you so much!  @fajri91
